/*
 */
package smith.patryk;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import static java.lang.System.exit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException; 

/**
 *
 * @author Patryk Smith
 */
public class EndScreen extends javax.swing.JPanel {
    private int score;
    private BufferedImage background;
    private InputStream audioInDirect;
    private AudioInputStream audioInBuffer;
    private Clip song;
    private final String audioClip = "/resources/WinSong.wav";
    private Starting mainMenu;
    private static FloatControl gainControl;
    
    /**
     * Creates new form EndScreen
     * @param _mainMenu
     * @param _score
     */
    public EndScreen(Starting _mainMenu, int _score){
        super();
        mainMenu = _mainMenu;
        initComponents();
        score = _score;
        try {
            //System.out.println(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/resources/TitleScreen1.wav")));
            InputStream url = getClass().getResourceAsStream("/resources/background.png");
            background = ImageIO.read(url);
            audioInDirect = getClass().getResourceAsStream(audioClip);
            InputStream bufferedIn = new BufferedInputStream(audioInDirect);
            audioInBuffer = AudioSystem.getAudioInputStream(bufferedIn);
            song = AudioSystem.getClip(); 
            song.open(audioInBuffer);
            gainControl = (FloatControl) song.getControl(FloatControl.Type.MASTER_GAIN);
            gainControl.setValue(Starting.soundVolume);
            
            song.stop();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Logger.getLogger(Starting.class.getName()).log(Level.SEVERE, null, ex);
        }
        //song.loop(1);
        
    }
   
    public void setScore(int _score){ 
        score = _score;
        jLabel1.setText("Score :   "+score + "");
    }
    
    @Override
    public void paintComponents(Graphics g){ 
        g.drawImage(background, 0, 0, null);
        g.setFont(new Font("Forte", Font.ITALIC, 18));
        g.drawString(score+"", background.getHeight(), background.getWidth());
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton1.setBorder(null);         
        jButton1.setBorderPainted(false);         
        jButton1.setContentAreaFilled(false);        
        jButton1.setOpaque(false);
        jButton2 = new javax.swing.JButton();
        jButton2.setBorder(null);         
        jButton2.setBorderPainted(false);         
        jButton2.setContentAreaFilled(false);        
        jButton2.setOpaque(false);

        setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Forte", 3, 48)); // NOI18N
        jLabel2.setText("You Win!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 11;
        add(jLabel2, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Forte", 3, 18)); // NOI18N
        jLabel1.setText("Score:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 23;
        add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        add(jLabel4, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Forte", 3, 18)); // NOI18N
        jButton1.setText("Main Menu");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        add(jButton1, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("Forte", 3, 18)); // NOI18N
        jButton2.setText("Quit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        add(jButton2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.out.println("Exiting Game...");
        exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void updateVolume(){
        gainControl.setValue(Starting.soundVolume);
    } 
    
    @Override
    public void paintComponent(Graphics g){ 
        g.drawImage(background, 0, 0, mainMenu.getSize().width ,mainMenu.getSize().height, this); 
        repaint(); 
    } 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mainMenu.setVisible(true);
        this.setVisible(false);
        this.score = 0;
        stopSong();
        mainMenu.startSong();
        mainMenu.restart();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setForeground(new Color(60,63,65));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setForeground(new Color(60,63,65));
    }//GEN-LAST:event_jButton2MouseExited

    
    public void startSong(){
        song.start();
    }
    public void stopSong(){
        song.stop();
        song.setFramePosition(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
