package customdatabase;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/** 
 * @author Patryk Smith
 */
public class ApplicationWindow extends javax.swing.JFrame {
   // JDBC driver name and database URL
    static final String JDBC_DRIVER = "org.apache.derby.jdbc.ClientDriver";
    static final String DB_URL = "jdbc:derby://localhost:1527/NEC";

    //  Database credentials
    static final String USER = "app";
    static final String PASS = "app";
     
    /**
     * Creates new form ApplicationWindow
     */
    public ApplicationWindow() {
        initComponents();
        jComboBox2.setVisible(false);
        jComboBox3.setVisible(false);
        jComboBox4.setVisible(false);
        jComboBox5.setVisible(false);
        jComboBox6.setVisible(false);
        jComboBox7.setVisible(false);

        jComboBox2.setSelectedIndex(-1);
        jComboBox3.setSelectedIndex(-1);
        jComboBox4.setSelectedIndex(-1);
        jComboBox5.setSelectedIndex(-1);
        jComboBox6.setSelectedIndex(-1);
        jComboBox7.setSelectedIndex(-1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conduit Tubing Fill", "Ampacity", "Equipment Grounding", "Service Grounding", "Motors Single Phase", "Motors Three Phase" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setSelectedIndex(-1);
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setSelectedIndex(-1);
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jComboBox4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.setSelectedIndex(-1);
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });

        jComboBox5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.setSelectedIndex(-1);
        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jComboBox6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox6.setSelectedIndex(-1);
        jComboBox6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox6ItemStateChanged(evt);
            }
        });

        jComboBox7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox7.setSelectedIndex(-1);
        jComboBox7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox7ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2, 0, 150, Short.MAX_VALUE)
                                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(15, 15, 15))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBox1, jComboBox2, jComboBox3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        int index = jComboBox1.getSelectedIndex();
        //TW, THHW, THW, THW-2
        switch (index) {
            //+=================================================================================+//
            case 0: // --------------------------- Conduit Size --------------------------- //
                // INPUTS:
                //      OPTION 1: PIPE TYPE
                //      OPTION 2: PIPE SIZE
                //      OPTION 3: INSULATION
                //      OPTION 4: WIRE GAUGE
                // OUTPUS:
                //      NUMBER OF CONDUCTORS
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"EMT", 
                                                                                        "ENT", 
                                                                                        "IMC", 
                                                                                        "FMC", 
                                                                                        "LFMC", 
                                                                                        "LFNC", 
                                                                                        "RMC", 
                                                                                        "PVC-SCH80", 
                                                                                        "PVC-SCH40"}));
                jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"3⁄8 inch", 
                                                                                        "1⁄2 inch", 
                                                                                        "3⁄4 inch", 
                                                                                        "1 inch", 
                                                                                        "1 1⁄4 inch", 
                                                                                        "1 1⁄2 inch", 
                                                                                        "2 inch", 
                                                                                        "2 1⁄2 inch", 
                                                                                        "3 inch", 
                                                                                        "3 1⁄2 inch", 
                                                                                        "4 inch"})); 
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"TW,THW,THHW,THW-2,RHH*,RHW*,RHW-2*",
                                                                                        "THHN, THWN, THWN-2",
                                                                                        "XHHW, ZW,XHHW-2,XHH",
                                                                                        "TFN, TFFN"}));
                jComboBox2.setSelectedIndex(-1);
                jComboBox3.setSelectedIndex(-1);
                jComboBox4.setSelectedIndex(-1);
                jComboBox5.setSelectedIndex(-1);
                jComboBox6.setSelectedIndex(-1);
                jComboBox7.setSelectedIndex(-1);
                jComboBox2.setVisible(true);
                jComboBox3.setVisible(true);
                jComboBox4.setVisible(true);
                jComboBox5.setVisible(false);
                jComboBox6.setVisible(false);
                jComboBox7.setVisible(false);
                break;
                //+=================================================================================+//
            case 1: // --------------------------- Ampacity --------------------------- //
                // INPUTS:
                //      OPTION 1: TEMPERATURE
                //      OPTION 2: COPPER / ALUMINUM 
                //      OPTION 3: WIRE GAUGE
                // OUTPUS:
                //      AMPS
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"60 C", "75 C" , "90 C"}));
                jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Copper", "Aluminum"}));
                jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"18 AWG",
                                                                                        "16 AWG",
                                                                                        "14 AWG",
                                                                                        "12 AWG",
                                                                                        "10 AWG",
                                                                                        "8 AWG",
                                                                                        "6 AWG",
                                                                                        "4 AWG",
                                                                                        "3 AWG",
                                                                                        "2 AWG",
                                                                                        "1 AWG",
                                                                                        "1/0 AWG",
                                                                                        "2/0 AWG",
                                                                                        "3/0 AWG",
                                                                                        "4/0 AWG",
                                                                                        "250 MCM",
                                                                                        "350 MCM",
                                                                                        "400 MCM",
                                                                                        "500 MCM",
                                                                                        "600 MCM",
                                                                                        "700 MCM",
                                                                                        "750 MCM",
                                                                                        "800 MCM",
                                                                                        "900 MCM",
                                                                                        "1000 MCM",
                                                                                        "1250 MCM",
                                                                                        "1500 MCM",
                                                                                        "1750 MCM", 
                                                                                        "2000 MCM"}));
                jComboBox2.setSelectedIndex(-1);
                jComboBox3.setSelectedIndex(-1);
                jComboBox4.setSelectedIndex(-1);
                jComboBox5.setSelectedIndex(-1);
                jComboBox6.setSelectedIndex(-1);
                jComboBox7.setSelectedIndex(-1);
                jComboBox2.setVisible(true);
                jComboBox3.setVisible(true);
                jComboBox4.setVisible(false);
                jComboBox5.setVisible(false);
                jComboBox6.setVisible(false);
                jComboBox7.setVisible(true);
                break;
                //+=================================================================================+//
            case 2: // --------------------------- Equipment Grounding --------------------------- //
                // INPUTS:
                //      OPTION 1: COPPER / ALUMINUM 
                //      OPTION 2: WIRE GAUGE
                // OUTPUS:
                //      AWG
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Copper", "Aluminum"}));
                jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"15 A", 
                                                                                        "20 A", 
                                                                                        "60 A", 
                                                                                        "100 A", 
                                                                                        "200 A", 
                                                                                        "300 A", 
                                                                                        "400 A", 
                                                                                        "500 A", 
                                                                                        "600 A", 
                                                                                        "800 A", 
                                                                                        "1000 A", 
                                                                                        "1200 A", 
                                                                                        "1600 A", 
                                                                                        "2000 A", 
                                                                                        "2500 A", 
                                                                                        "3000 A", 
                                                                                        "4000 A", 
                                                                                        "5000 A", 
                                                                                        "6000 A"}));
                jComboBox2.setSelectedIndex(-1);
                jComboBox3.setSelectedIndex(-1);
                jComboBox4.setSelectedIndex(-1);
                jComboBox5.setSelectedIndex(-1);
                jComboBox6.setSelectedIndex(-1);
                jComboBox7.setSelectedIndex(-1);
                jComboBox2.setVisible(true);
                jComboBox3.setVisible(true);
                jComboBox4.setVisible(false);
                jComboBox5.setVisible(false);
                jComboBox6.setVisible(false);
                jComboBox7.setVisible(false);
                break;
                //+=================================================================================+//
            case 3: // --------------------------- Service Grounding ---------------------------//
                // INPUTS:
                //      OPTION 1: COPPER / ALUMINUM 
                //      OPTION 2: WIRE GAUGE
                // OUTPUS:
                //      AWG
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Copper", "Aluminum"})); 
                jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Copper", "Aluminum"})); 
                jComboBox2.setSelectedIndex(-1);
                jComboBox3.setSelectedIndex(-1);
                jComboBox4.setSelectedIndex(-1);
                jComboBox5.setSelectedIndex(-1);
                jComboBox6.setSelectedIndex(-1);
                jComboBox7.setSelectedIndex(-1);
                jComboBox2.setVisible(true);
                jComboBox3.setVisible(true);
                jComboBox4.setVisible(true);
                jComboBox5.setVisible(false);
                jComboBox6.setVisible(false);
                jComboBox7.setVisible(false);
                break;
                //+=================================================================================+//
            case 4: // --------------------------- Motors Single Phase ---------------------------//
                // INPUTS:
                //      OPTION 1: VOLTAGE
                //      OPTION 2: HORSEPOWER
                // OUTPUS:
                //      AMPERES
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"115 V", 
                                                                                        "200 V", 
                                                                                        "208 V", 
                                                                                        "230 V"}));
                jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1/6 hp", 
                                                                                        "1/4 hp", 
                                                                                        "1/3 hp", 
                                                                                        "1/2 hp", 
                                                                                        "3/4 hp", 
                                                                                        "1 hp", 
                                                                                        "1 1/2 hp", 
                                                                                        "2 hp", 
                                                                                        "3 hp", 
                                                                                        "5 hp", 
                                                                                        "7 1/2 hp", 
                                                                                        "10 hp"}));
                jComboBox2.setSelectedIndex(-1);
                jComboBox3.setSelectedIndex(-1);
                jComboBox4.setSelectedIndex(-1);
                jComboBox5.setSelectedIndex(-1);
                jComboBox6.setSelectedIndex(-1);
                jComboBox7.setSelectedIndex(-1);
                jComboBox2.setVisible(true);
                jComboBox3.setVisible(true);
                jComboBox4.setVisible(false);
                jComboBox5.setVisible(false);
                jComboBox6.setVisible(false);
                jComboBox7.setVisible(false);
                break;
                //+=================================================================================+//
            case 5: // --------------------------- Motors Three Phase ---------------------------//
                // INPUTS:
                //      OPTION 1: VOLTAGE
                //      OPTION 2: HORSEPOWER
                // OUTPUS:
                //      AMPERES
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"115 V", 
                                                                                        "200 V", 
                                                                                        "208 V", 
                                                                                        "230 V", 
                                                                                        "460 V", 
                                                                                        "575 V", 
                                                                                        "2300 V"}));
                jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1⁄2 hp",
                                                                                        "3⁄4 hp",
                                                                                        "1 hp",
                                                                                        "1 1⁄2 hp",
                                                                                        "2 hp",
                                                                                        "3 hp",
                                                                                        "5 hp",
                                                                                        "7 1⁄2 hp",
                                                                                        "10 hp",
                                                                                        "15 hp",
                                                                                        "20 hp",
                                                                                        "25 hp",
                                                                                        "30 hp",
                                                                                        "40 hp",
                                                                                        "50 hp",
                                                                                        "60 hp",
                                                                                        "75 hp",
                                                                                        "100 hp",
                                                                                        "125 hp",
                                                                                        "150 hp",
                                                                                        "200 hp",
                                                                                        "250 hp",
                                                                                        "300 hp",
                                                                                        "350 hp",
                                                                                        "400 hp",
                                                                                        "450 hp",
                                                                                        "500 hp"}));
                jComboBox2.setSelectedIndex(-1);
                jComboBox3.setSelectedIndex(-1);
                jComboBox4.setSelectedIndex(-1);
                jComboBox5.setSelectedIndex(-1);
                jComboBox6.setSelectedIndex(-1);
                jComboBox7.setSelectedIndex(-1);
                jComboBox2.setVisible(true);
                jComboBox3.setVisible(true);
                jComboBox4.setVisible(false);
                jComboBox5.setVisible(false);
                jComboBox6.setVisible(false);
                jComboBox7.setVisible(false);
                break;
                //+=================================================================================+//
            default:
                break;
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged
     
    // --------------------------------- Update the result for each change in input ------------------------------------------ //
    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        int index1 = jComboBox1.getSelectedIndex();
        int index2 = jComboBox2.getSelectedIndex();
        if (index1 != 3) {
            try {
                update();
            } catch (SQLException ex) {
                Logger.getLogger(ApplicationWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            switch(index2){
                case 0:
                    jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"2 AWG or smaller", 
                                                                                            "1 AWG or 1/0 AWG", 
                                                                                            "2/0 AWG or 3/0 AWG", 
                                                                                            "Over 3/0 AWG through 350 MCM", 
                                                                                            "Over 350 MCM through 600 MCM", 
                                                                                            "Over 600 MCM through 1100 MCM", 
                                                                                            "Over 1100 MCM"})); 
                    break;
                case 1:
                    jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1/0 AWG or smaller", 
                                                                                            "2/0 AWG or 3/0",
                                                                                            "4/0 AWG or 250 MCM",
                                                                                            "Over 250 through 500 MCM", 
                                                                                            "Over 500 MCM through 900 MCM", 
                                                                                            "Over 900 MCM through 1750 MCM", 
                                                                                            "Over 1750 MCM"})); 
                    break;
                default:
                    break;
            } 
            jComboBox4.setSelectedIndex(-1); 
            jComboBox4.setVisible(true);
            try {
                update();
            } catch (SQLException ex) {
                Logger.getLogger(ApplicationWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        try {
            update();
        } catch (SQLException ex) {
            Logger.getLogger(ApplicationWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        try {
            update();
        } catch (SQLException ex) {
            Logger.getLogger(ApplicationWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        int index4 = jComboBox4.getSelectedIndex();
        int index1 = jComboBox1.getSelectedIndex();
        //"TW/THW/THHW/THW-2/RHH*/RHW*/RHW-2*",
        //THHN, THWN, THWN-2
        //XHHW, ZW,XHHW-2,XHH
        if (index1 == 0) {
            switch (index4) {
                case 0: // "6","4","3","2","1","1/0" ,"2/0","3/0","4/0" ,"250","300" ,"350","400" ,"500","600","700","750","800","900","1000" ,"1250" ,"1500","1750","2000"
                    jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"6",
                        "4 AWG",
                        "3 AWG",
                        "2 AWG",
                        "1 AWG",
                        "1/0",
                        "2/0",
                        "3/0",
                        "4/0",
                        "250 MCM",
                        "300 MCM",
                        "350 MCM",
                        "400 MCM",
                        "500 MCM",
                        "600 MCM",
                        "700 MCM",
                        "750 MCM",
                        "800 MCM",
                        "900 MCM",
                        "1000 MCM",
                        "1250 MCM",
                        "1500 MCM",
                        "1750 MCM",
                        "2000 MCM"}));
                    jComboBox5.setSelectedIndex(-1);
                    jComboBox5.setVisible(true);
                    break;
                case 1: //"14 ","12","10 ","8","6 ","4","3 ","2","1 ","1/0","2/0","3/0","4/0 ","250 ","300 ","350 ","400 ","500","600 ","700","750 ","800","900 ","1000"  
                    jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"14",
                        "12 AWG",
                        "10 AWG",
                        "8 AWG",
                        "6 AWG",
                        "4 AWG",
                        "3 AWG",
                        "2 AWG",
                        "1 AWG",
                        "1/0",
                        "2/0",
                        "3/0",
                        "4/0",
                        "250 MCM",
                        "300 MCM",
                        "350 MCM",
                        "400 MCM",
                        "500 MCM",
                        "600 MCM",
                        "700 MCM",
                        "750 MCM",
                        "800 MCM",
                        "900 MCM",
                        "1000 MCM"}));
                    jComboBox5.setSelectedIndex(-1);
                    jComboBox5.setVisible(true);
                    break;
                case 2:
                    jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"14",
                        "12 AWG",
                        "10 AWG",
                        "8 AWG",
                        "6 AWG",
                        "4 AWG",
                        "3 AWG",
                        "2 AWG",
                        "1 AWG",
                        "1/0",
                        "2/0",
                        "3/0",
                        "4/0",
                        "250 MCM",
                        "300 MCM",
                        "350 MCM",
                        "400 MCM",
                        "500 MCM",
                        "600 MCM",
                        "700 MCM",
                        "750 MCM",
                        "800 MCM",
                        "900 MCM",
                        "1000 MCM",
                        "1250 MCM",
                        "1500 MCM",
                        "1750 MCM",
                        "2000 MCM"}));
                    jComboBox5.setSelectedIndex(-1);
                    jComboBox5.setVisible(true);
                    break;
                case 3:

                    jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"18",
                        "16"}));
                    jComboBox5.setSelectedIndex(-1);
                    jComboBox5.setVisible(true);
                    break;
                default:
                    break;
            }
        }

    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
        try {
            update();
        } catch (SQLException ex) {
            Logger.getLogger(ApplicationWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    private void jComboBox6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox6ItemStateChanged
        try {
            update();
        } catch (SQLException ex) {
            Logger.getLogger(ApplicationWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox6ItemStateChanged

    private void jComboBox7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox7ItemStateChanged
        try {
            update();
        } catch (SQLException ex) {
            Logger.getLogger(ApplicationWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox7ItemStateChanged

    public void update() throws SQLException {
        
        Connection conn = null;
        Statement stmt = null;
        String sql = " ";
          
        try {
            Class.forName(JDBC_DRIVER);      
            conn = DriverManager.getConnection(DB_URL, USER, PASS);          
            stmt = conn.createStatement(); 
        } catch (ClassNotFoundException ex) { 
            Logger.getLogger(ApplicationWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int value1 = jComboBox1.getSelectedIndex();
        int value2 = jComboBox2.getSelectedIndex();
        int value3 = jComboBox3.getSelectedIndex();
        int value4 = jComboBox4.getSelectedIndex();
        int value5 = jComboBox5.getSelectedIndex();
        int value6 = jComboBox6.getSelectedIndex();
        int value7 = jComboBox7.getSelectedIndex();
        switch (value1){
            case 1:     // Ampacity
                if((value2 != -1) && (value3 != -1) && (value7 != -1)){
                    String temperature = jComboBox2.getSelectedItem().toString(),  
                           wireType = jComboBox3.getSelectedItem().toString(),
                           wireSize = jComboBox7.getSelectedItem().toString();
                     
                    sql = "SELECT temperature, wireType, wireSize, amps FROM ampacity WHERE temperature = '"+temperature+"' AND wireType = '"+wireType+"' AND wireSize = '" + wireSize + "'";
                    try (ResultSet rs = stmt.executeQuery(sql)) { 
                        while (rs.next())  {
                            jLabel1.setText(rs.getString("amps"));
                        }
                    }
                } 
                break;
            case 2:     // Equipemnt Ground
                if((value2 != -1) && (value3 != -1)){
                    String wireType = jComboBox2.getSelectedItem().toString(),  
                           maxAmps = jComboBox3.getSelectedItem().toString();
                     
                    sql = "SELECT maxAmps, wireSize, wireType FROM groundingEquipment WHERE maxAmps = '"+maxAmps+"' AND wireType = '"+wireType+"'";
                    try (ResultSet rs = stmt.executeQuery(sql)) { 
                        while (rs.next())  {
                            jLabel1.setText(rs.getString("wireSize"));
                        }
                    }
                } 
                break;
            case 3:     // Service Ground
                if((value2 != -1) && (value3 != -1) && (value4 != -1)){
                    String metalType = jComboBox2.getSelectedItem().toString(), 
                           metalSize = jComboBox4.getSelectedItem().toString(), 
                           desiredType = jComboBox3.getSelectedItem().toString();
                     
                    sql = "SELECT metalType, metalSize, desiredType, desiredMetalSize FROM groundingService WHERE metalType = '"+metalType+"' AND metalSize = '"+metalSize+"' AND desiredType = '" +desiredType+"'";
                    try (ResultSet rs = stmt.executeQuery(sql)) { 
                        while (rs.next())  {
                            jLabel1.setText(rs.getString("desiredMetalSize"));
                        }
                    }
                } 
                break;
            case 4:     // Motor 1 Phase
                if((value2 != -1) && (value3 != -1)){
                    String voltage = jComboBox2.getSelectedItem().toString(), horsePower = jComboBox3.getSelectedItem().toString(); 
                    sql = "SELECT voltage, horsePower, amps FROM motorSinglePhase WHERE voltage = '"+voltage+"' AND horsePower = '"+horsePower+"'";
                    try (ResultSet rs = stmt.executeQuery(sql)) { 
                        while (rs.next())  {
                            jLabel1.setText(rs.getString("AMPS"));
                        }
                    }
                } 
                break;
            case 5:     // Motor 3 Phase
                if((value2 != -1) && (value3 != -1)){
                    String voltage = jComboBox2.getSelectedItem().toString(), horsePower = jComboBox3.getSelectedItem().toString(); 
                    sql = "SELECT voltage, horsePower, amps FROM motorThreePhase WHERE voltage = '"+voltage+"' AND horsePower = '"+horsePower+"'";
                    try (ResultSet rs = stmt.executeQuery(sql)) { 
                        while (rs.next())  {
                            jLabel1.setText(rs.getString("AMPS"));
                        }
                    }
                } 
                break;
            default:
                break;
        }
        try { 
            stmt.close();
            conn.close();
        } catch (SQLException se) { 
             Logger.getLogger(ApplicationWindow.class.getName()).log(Level.SEVERE, null, se);
        } finally { 
            if (stmt != null) {
                stmt.close();
            }
            if (conn != null) {
                conn.close();
            } 
        }
        
    };


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
