/*
 */
package customdatabase;

 
import static customdatabase.SearchDatabase.DB_URL;
import static customdatabase.SearchDatabase.JDBC_DRIVER;
import static customdatabase.SearchDatabase.PASS;
import static customdatabase.SearchDatabase.USER;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List; 
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Patryk Smith
 */
public class DeleteDatabase extends javax.swing.JPanel {
    private List<String> s;
    private Connection conn = null;
    private Statement stmt = null;
    private String sql = " ";
    /**
     * Creates new form DeleteDatabase
     */
    public DeleteDatabase() {
        initComponents();
         
        try {
            Class.forName(JDBC_DRIVER);            
            conn = DriverManager.getConnection(DB_URL, USER, PASS);            
            stmt = conn.createStatement();  
            s = new ArrayList<>();
            sql = "SELECT * FROM cars";
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                s.add("Make : " +rs.getString("make").trim()+",   Model : " +rs.getString("MODEL").trim()+",   Engine Size : " +rs.getString("ENGINESIZE").trim()+",   Year : " +rs.getString("YR").trim() );
            } 
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SearchDatabase.class.getName()).log(Level.SEVERE, null, ex);
        }  
        jList1.setModel(new javax.swing.AbstractListModel<String>() { 
            @Override
            public int getSize() { return s.size(); }
            @Override
            public String getElementAt(int i) { return s.get(i); }
        });  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        add(jButton1, gridBagConstraints);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(jScrollPane1, gridBagConstraints);

        jButton2.setText("Delete Selected");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        add(jButton2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainScreen.mainWindow.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            ResultSet rs = null;
            Class.forName(JDBC_DRIVER);            
            conn = DriverManager.getConnection(DB_URL, USER, PASS);            
            stmt = conn.createStatement();
            String make, model ="", year="", engineSize="";
            for(String s: jList1.getSelectedValuesList()){
                make =  s.substring(s.indexOf("Make : ")+7, (s.indexOf("Model :")-2));
                model =  s.substring(s.indexOf("Model : ")+8, (s.indexOf("Engine Size :")-2));
                engineSize =  s.substring(s.indexOf("Engine Size : ")+14, (s.indexOf("Year :")-2));
                year =  s.substring(s.indexOf("Year : ")+7);
                
                make = make.substring(0,make.indexOf(","));
                model = model.substring(0,model.indexOf(","));
                engineSize = engineSize.substring(0,engineSize.indexOf(","));  
                sql = "DELETE FROM cars WHERE make = '" + make + "' AND model = '" + model + "' AND YR = " +year +" AND engineSize = "+engineSize +"";
                stmt.executeUpdate(sql);
                
            } 
            s = new ArrayList<>(); 
            sql = "SELECT * FROM cars";
            rs = stmt.executeQuery(sql);
            while (rs.next()) {
                s.add("Make : " +rs.getString("make").trim()+",   Model : " +rs.getString("MODEL").trim()+",   Engine Size : " +rs.getString("ENGINESIZE").trim()+",   Year : " +rs.getString("YR").trim() );
            } 
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SearchDatabase.class.getName()).log(Level.SEVERE, null, ex);
        }  
        jList1.setModel(new javax.swing.AbstractListModel<String>() { 
            @Override
            public int getSize() { return s.size(); }
            @Override
            public String getElementAt(int i) { return s.get(i); }
        });
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
