/*
 */
package customdatabase;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Patryk Smith
 */
public class SearchDatabase extends javax.swing.JPanel {

    // JDBC driver name and database URL
    static final String JDBC_DRIVER = "org.apache.derby.jdbc.ClientDriver";
    static final String DB_URL = "jdbc:derby://localhost:1527/CARS";

    //  Database credentials
    static final String USER = "app";
    static final String PASS = "app";

    /**
     * Creates new form SearchDatabase
     */
    public SearchDatabase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make", "Model", "Engine Size", "Year" }));
        jComboBox1.setSelectedIndex(-1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(jComboBox1, gridBagConstraints);

        jLabel1.setText("Search by :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        add(jLabel1, gridBagConstraints);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        add(jButton1, gridBagConstraints);

        jTextField1.setPreferredSize(new java.awt.Dimension(100, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 12;
        add(jTextField1, gridBagConstraints);

        jLabel2.setText("Value :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("Result :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(jLabel3, gridBagConstraints);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 100));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        add(jScrollPane1, gridBagConstraints);

        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jButton2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Connection conn = null;
        Statement stmt = null;
        String sql = " ";
        
        try {
            Class.forName(JDBC_DRIVER);            
            conn = DriverManager.getConnection(DB_URL, USER, PASS);            
            stmt = conn.createStatement();            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SearchDatabase.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
        if(!jTextField1.getText().equals("")){
            String s = "";
            if(jComboBox1.getSelectedItem().toString().equals("Year")){
                sql = "SELECT * FROM cars WHERE YR = " + jTextField1.getText() + "";
            }else if(jComboBox1.getSelectedItem().toString().equals("Engine Size")){
                sql = "SELECT * FROM cars WHERE EngineSize = " + jTextField1.getText() + "";
            }else{
                sql = "SELECT * FROM cars WHERE "+jComboBox1.getSelectedItem().toString()+" = '" + jTextField1.getText() + "'";
            }

            try (ResultSet rs = stmt.executeQuery(sql)) {                        
                while (rs.next()) {
                    s +=("Make : " +rs.getString("make").trim()+",   Model : " +rs.getString("MODEL").trim()+",   Engine Size : " +rs.getString("ENGINESIZE").trim()+",   Year : " +rs.getString("YR").trim() + '\n');
                 }
                jTextArea1.setText(s);

            } catch (SQLException ex) {
                Logger.getLogger(SearchDatabase.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainScreen.mainWindow.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
